version: '3.9'

services:
  backend:
    build: .
    container_name: modernfarmstay-backend
    command: gunicorn modernfarmstay.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - /var/www/modernfarmstay/static:/app/staticfiles
    ports:
      - "8020:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    networks:
      - modernfarm-net

  db:
    image: postgres:15
    container_name: modernfarmstay-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: modernfarmstay
      POSTGRES_USER: farmuser
      POSTGRES_PASSWORD: farmpass
    networks:
      - modernfarm-net

volumes:
  postgres_data:

networks:
  modernfarm-net:
